### ISSUE TITLE
Semantics of E.log and E.bind

### ISSUE THREAD

**Issue by rand00** [dbuenzli/note#1]
I know this is a work in progress, but you linked the lib in a thread on discuss.ocaml, so I guess you wanted some eyes on it (: As I read through the interface of `E` I became a bit confused about the semantics stated in the comments. 

It states
https://github.com/dbuenzli/note/blob/2257dbecd10ac1d07ffd51f5d4c51dad88dc8dd3/src/note.mli#L110-L112

.. which I interpret as if `e = E.never`, then `log` will return `None`. This, mixed with the definition of `bind`, confuses me. 
https://github.com/dbuenzli/note/blob/2257dbecd10ac1d07ffd51f5d4c51dad88dc8dd3/src/note.mli#L134-L139
.. which I understand as `bind` returning `never` if there has never been an event on `e`. 
I expected
* that `E.log E.never foo = None`
* that `E.log (E.bind e foo) = None` if there had never happened an event on `e` (which I think would be weird)

Then I tried it, and neither the first nor the second expectation was the case - when does `E.log` actually return `None`?

Also, for the documentation of `E.log`, the expression `Logr.(create ?now (const f $ obs e))` doesn't conform to the interface of `E.obs`, which returns an `'a option Logr.obs`

**Comment by dbuenzli** [comment]
> .. which I understand as `bind` returning `never` if there has never been an event on `e`.

It doesn't *return* `never`, it has the same *denotation* as never before an event occurs on `e` (the right hand side should be tweaked to read `[never{_t}]`.

**Comment by rand00** [comment]
Sorry, bad choice of words - I was more thinking in terms of equivalence. That change clears a bit up, but how does it make sense that `bind`s denotation is `[f v]_t` when `[e]_<=t = Some v`? Why is it not `[f v]_t` when `[e]_t = Some v`? If I misunderstand the semantics of it fundamentally, could you point me in a direction of some material for understanding?

**Comment by rand00** [comment]
In my mind `[e]_<=t = Some v` can mean two things, either
* there *exist* an earlier/current `e` that had `Some v` as its denotation, where I mean that if `e` was ever `Some v`, then `[bind e f]_t` *will* have the denotation `[f v_<=t]_t`
* or the exact `e` that `[bind e f]_t` operates on, *can* be of an earlier time, where I mean that `e` and `bind` possibly isn't synchronized at the same point in time

.. and I don't understand why either would be the semantics you want. Are one not guaranteed that if you `map` or `bind` on an event, the resulting event will be of the same time as the source event?

**Comment by dbuenzli** [comment]
The semantic notations are the same as those of react which are defined [here](https://erratique.ch/software/react/doc/React.html#sem). 

> Are one not guaranteed that if you `map` or `bind` on an event, the resulting event will be of the same time as the source event?

No. The semantics means you have the same semantics as the event that was given back to you by mapping the last occurence of `e` by `f`. 

Another way of saying this is that `bind` is an event source switcher. It's an event whose source may be changed on each occurence of `e`.

**Comment by rand00** [comment]
I see, so my confusion was based on me thinking of `e`s as instantaneous events, in relation to the denotational semantics, instead of event-*sources*. The connotations I have in relation to the word *event* is something that happens at a specific point - whereas an event-source to me sounds more like a thing that can be parameterized by time, to produce an event. Weird that I havn't thought about this terminology semantics explicitly before, as I've been using FRP quite a lot... 

The word *signal* I think better fits the semantics of a time-varying value, where it's obvious to call the value at time `t` 'the value of the signal'. For events it feels unnatural for me to call the instantaneous events for *occurrences* of a (single) event.

Concerning the earlier question of `E.log`, when will it *return* (  (; ) `None`?

``` ocaml
λ » E.log E.never print_endline ;;
- : Logr.t option = Some <abstr>
```

**Comment by dbuenzli** [comment]
> Weird that I havn't thought about this terminology semantics explicitly before, as I've been using FRP quite a lot...

FRP has always, including in the first paper, used the term *event* for representing sequences of *event occurrences*. 

Note that events can perfectly be represented by signals (`'a event = 'a option signal`) but since those are really point-wise it's better to treat them differently; otherwise you observe them both when the event occurs (that is changes to `Some _`) and when it no longer occurs (changes back an infinitesimal step after to `None`) which is most of the time wasteful.

> Concerning the earlier question of `E.log`, when will it _return_ ( (; ) `None`?

Never for now.

**Comment by dbuenzli** [comment]
(reopening so that I remember at least correcting the doc string)
