### ISSUE TITLE
Note_brr_kit and Pointer

### ISSUE THREAD

**Issue by nickbetteridge** [dbuenzli/note#6]
I'm just getting to up to speed with Note and Note_brr_kit, and trying to get the brr mouse example to work with touch - am I correct in thinking that Note_brr_kit needs a Pointer module, or is there a fiendish trick that I've missed to make pointers work with note and brr kit?

**Comment by dbuenzli** [comment]
Your thinking is correct.

**Comment by nickbetteridge** [comment]
I that case, unless you have any objections, I'll do my best and offer a PR

**Comment by dbuenzli** [comment]
Thank you but as noted in the docs the whole `Note` stuff remains experimental for now. I'd rather not take any PR for now. I think it will be easier for you if you devise your own via what is provided in `Note_brr` – even though that's still no guarantee.

**Comment by nickbetteridge** [comment]
OK - no problem
